### PR TITLE
Resolve packaging issues.

### PR DESCRIPTION
**Pull request by thecatrine**
Issue: 
https://github.com/airgap-it/beacon-sdk/issues/138

The issue here appears to be overlapping compatibility issues with imports of the form `import * from 'blah'`.

With `"esModuleInterop": true` in tsconfig.json, tsc will attempt to treat `import * from libsodium-wrappers` as the following:
```
var sodium = __importStar(require("libsodium-wrappers"));
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
```
However libsodium-wrappers seems to do something not quite standard with its exports,  resulting in only some of the properties being on the `result` object, and the needed ones (e.g. crypto_generichash) on the `sodium.default` object.

tsc docs suggest nonstandard exports use `import sodium from  libsodium-wrappers` which produces:
```
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
exports.__esModule = true;
var beacon_sdk_1 = require("@airgap/beacon-sdk");
var libsodium_wrappers_1 = __importDefault(require("libsodium-wrappers"));
```

Using this style of import simplifies the build a bit in the tests. It appears that this behavior used to work before recent versions of Babel, and potentially in React, which might explain some of the weird behavior.

### CODE REVIEW

**Comment by thecatrine** [comment]
cc @AndreasGassmann

**Comment by clemsos** [comment]
This PR does not seem to build. I got the following error during the `npm run build` step(installing with yarn and node 14)

It seems like [UglifyJS does not support ES6](https://stackoverflow.com/questions/47439067/uglifyjs-throws-unexpected-token-keyword-const-with-node-modules).

```
> @airgap/beacon-sdk@2.3.5 browserify /Users/clemsos/Library/Caches/Yarn/v6/.tmp/ccbafba1a6a547919b5429c1a6dc7686.4531c670b2386cbe2323769af69ec0ee6734c0e3.prepare
> tsc -p ./tsconfig-browserify.json && browserify ./dist/browserify/index.js -s beacon | uglifyjs > ./dist/walletbeacon.min.js && rm -rf dist/browserify

Parse error at 0:12818,0
const asn1 = exports;
^
ERROR: Unexpected token: keyword «const»
    at JS_Parse_Error.get (eval at <anonymous> (/Users/clemsos/Library/Caches/Yarn/v6/.tmp/ccbafba1a6a547919b5429c1a6dc7686.4531c670b2386cbe2323769af69ec0ee6734c0e3.prepare/node_modules/uglify-js/tools/node.js:18:1), <anonymous>:71:23)
    at fatal (/Users/clemsos/Library/Caches/Yarn/v6/.tmp/ccbafba1a6a547919b5429c1a6dc7686.4531c670b2386cbe2323769af69ec0ee6734c0e3.prepare/node_modules/uglify-js/bin/uglifyjs:334:27)
    at run (/Users/clemsos/Library/Caches/Yarn/v6/.tmp/ccbafba1a6a547919b5429c1a6dc7686.4531c670b2386cbe2323769af69ec0ee6734c0e3.prepare/node_modules/uglify-js/bin/uglifyjs:277:9)
    at Socket.<anonymous> (/Users/clemsos/Library/Caches/Yarn/v6/.tmp/ccbafba1a6a547919b5429c1a6dc7686.4531c670b2386cbe2323769af69ec0ee6734c0e3.prepare/node_modules/uglify-js/bin/uglifyjs:200:9)
    at Socket.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @airgap/beacon-sdk@2.3.5 browserify: `tsc -p ./tsconfig-browserify.json && browserify ./dist/browserify/index.js -s beacon | uglifyjs > ./dist/walletbeacon.min.js && rm -rf dist/browserify`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @airgap/beacon-sdk@2.3.5 browserify script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by thecatrine** [comment]
@clemsos I had to add the package locally to get it to build with parcel. If I have a second I can try to get it to build in both, but that might work if you're just trying to get it to run in the browser with your build system

**Comment by clemsos** [comment]
ok seems like bumping uglifyJS version is enough to solve the issue. I added a PR here https://github.com/thecatrine/beacon-sdk/pull/1

**Comment by AndreasGassmann** [comment]
Hi guys. First of all I would like to apologise for the lack of communication from our side, and thank you for all the effort you put in.

A while ago I tried to fix the build issue by taking the [taquito](https://github.com/ecadlabs/taquito) build as inspiration. At the time, there were some issues that came up that I could couldn't get around. My (failed) attempt can be found here: https://github.com/airgap-it/beacon-sdk/pull/171/files. I did release a few test versions along the way, but something always broke.

We then decided to convert the beacon-sdk to a multi-package architecture: https://github.com/airgap-it/beacon-sdk/pull/253. As part of this change, I wanted to take another look at the build issues. Sadly, the multi-package architecture change was delayed, so with it, looking at the build issue was delayed as well. Now I have time to work on this again and hope to finish it by the end of this week.

While I didn't try this branch out directly just yet, I applied all the changes step by step in the multi-package branch: https://github.com/airgap-it/beacon-sdk/pull/253. I released those packages to NPM as a beta. But sadly, the changes in this branch don't seem to be working in a standard angular project. I get the following error multiple times: 

Screenshot 2021-11-08 at 17 10 52

Maybe I didn't apply all the changes from this branch and forgot something, so I'll try to use this branch tomorrow and see if it works.

If you want to try it out, the packages are on npm (make sure that you use the next release): https://www.npmjs.com/search?q=%40airgap%2Fbeacon

I would be happy for any feedback. I noticed that in my try just now, Angular is trying to include the cjs files, and I think in the current version of the beacon-sdk, it is using the esm files (which is preferred). So maybe I do indeed have something misconfigured in my branch.

**Comment by AndreasGassmann** [comment]
@thecatrine @clemsos could you try out `"@airgap/beacon-dapp": "0.0.1-beta.12"` and let me know if that works for you? This is a beta version of the new multi-package architecture, so it's not a drop-in replacement (yet).

I can now use this version in my angular app, but I was also able to remove most of the workarounds we had in the build before. So I'm curious if that also fixes the issues on your side.

**Comment by prashantpawar** [comment]
@AndreasGassmann I was having a similar sodium issue but after trying out the `0.0.1-beta.12` issue, its fixed now. Thank you!

**Review by AndreasGassmann — APPROVED** [review]

**Comment by AndreasGassmann** [comment]
@prashantpawar Thanks for testing.

I will merge this PR now and then also merge my multi package branch. This will result in a slightly different setup than the one here, but hopefully that one works for everyone.

**Pull request merged**
