### PR TITLE
feat(wallet): add exodus

### PR DESCRIPTION
**Pull request by RichAyotte**
## Summary
Adds Exodus to the list of wallets.

### Note
_A double scrollbar issue has appeared when another wallet was added that should be addressed in a separate PR._

### CODE REVIEW

**Comment by AndreasGassmann** [comment]
Thanks for the PR. Can this be merged now? And is this deeplink correct?

`exodus://wc?uri=`

Because it looks like a WC deeplink.

**Comment by RichAyotte** [comment]
@AndreasGassmann when I click the Exodus wallet, the link points to `tezos://?type=tzip10&data=...` instead of `exodus://wc?uri=...` is this correct?

**Review by AndreasGassmann — APPROVED** [review]

**Comment by RichAyotte** [comment]
The Exodus mobile wallet has consolidated Beacon with WalletConnect in a way that using `exodus://wc?uri=...` is correct however I have not been able to test this yet. It seems that on Android, the link provided by the Beacon UI package is `tezos://...` instead of  `exodus://...`. I'm not sure if this is the correct or desired behaviour.

**Comment by AndreasGassmann** [comment]
> It seems that on Android, the link provided by the Beacon UI package is tezos://... instead of exodus://.... I'm not sure if this is the correct or desired behaviour.

Yes, this behaviour is correct. On iOS, the `tezos://` deeplink will open a random wallet, which is why it needs to be the specific `exodus://` deeplink. But on Android, there is a selection from the OS.

I merged your branch into a branch in this repo so all the pipelines will run.

**Comment by RichAyotte** [comment]
If the user explicitly selects Exodus from the Beacon UI, why is the generic `tezos:` app scheme used instead of the more specific `exodus:`? It feels like an unnecessary extra step.

**Comment by AndreasGassmann** [comment]
In the current UI, this would make sense, yes. In the old UI, the Android view didn't show any wallet options, it only had one button to connect, which is why the behaviour has historically been like this.

**Pull request merged**
