### PR TITLE
fix(beacon-ui): make qrcode work with rollup/vite

### PR DESCRIPTION
**Pull request by souljorje**
TL;DR: if you don't plan to use namespaced imports from CJS don't use `import *` otherwise rollups' [output.interop](https://rollupjs.org/guide/en/#outputinterop) breaks usage of default exported function. 

related: 
https://github.com/airgap-it/beacon-sdk/issues/170
https://github.com/rollup/rollup/issues/1267
https://github.com/kazuhikoarase/qrcode-generator/issues/62

### CODE REVIEW

**Comment by itsnamangoyal** [comment]
We are also using vite for framework and production app is missing qrcode.

**Comment by itsnamangoyal** [comment]
@AndreasGassmann  Can you look into this one with a higher priority 😅? thank you

**Comment by souljorje** [comment]
@itsnamangoyal here's a workaround https://github.com/airgap-it/beacon-sdk/issues/170#issuecomment-1127958339

**Comment by AndreasGassmann** [comment]
Hi, sorry for getting back to you so late.

Thanks for creating this PR. Historically, we had a lot of issues with different build environments, primarily because of the QR dependency and libsodium. It usually works with Angular / Webpack (which we use most), but it frequently had issues with other systems.

Before I merge this, I would like to make sure that this doesn't introduce a regression for other frameworks such as Angular. Once I can confirm that it also works there, I will merge it.

**Comment by PureSpider** [comment]
@AndreasGassmann any news on this?

**Comment by AndreasGassmann** [comment]
Hi. Sorry for the delay (again).

We have finally replaced `libsodium` in `3.2.0`, now I'd like to tackle this. I will merge it into a branch so I can release a beta version from our CI.

**Comment by RichAyotte** [comment]
@AndreasGassmann I noticed https://github.com/airgap-it/beacon-sdk/tree/fix/qr-build-issues hasn't been merged yet. Is anything more needed for this?

**Pull request merged**
